# The URL the site will be built for
base_url = "https://drsheppard01.github.io/"
theme = "apollo"
generate_feeds = true
taxonomies = [{ name = "tags" }]


# The site title and description; used in feeds by default.
title = "Dr. Sheppard's blog"

# The default site author.
author = "Dr. Sheppard"

# No SASS - CSS is internal (located in base.html template).
compile_sass = true
minify_html = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra]
toc = true
theme = "toggle"              # light, dark, auto, toggle, toggle-auto
mathjax = false
fediverse = true    # author attribution
fediverse_creator = "@drsheppard@social.linux.pizza"    # e.g. @user@instance


menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "Bluesky", url = "https://bsky.app/profile/drsheppard01.bsky.social", icon = "bluesky" },
    { name = "Mastodon", url = "https://social.linux.pizza/@drsheppard/", icon = "mastodon" },
]

stylesheets = [
  "custom.css",
]

[extra.taxonomies]
sort_by = "page_count"         # e.g. name, page_count
reverse = true

[extra.analytics]
enabled = false